package models

// Define constant values for AmfEventType
const (
	AMFEVENTTYPE_LOCATION_REPORT                       string = "LOCATION_REPORT"
	AMFEVENTTYPE_PRESENCE_IN_AOI_REPORT                string = "PRESENCE_IN_AOI_REPORT"
	AMFEVENTTYPE_TIMEZONE_REPORT                       string = "TIMEZONE_REPORT"
	AMFEVENTTYPE_ACCESS_TYPE_REPORT                    string = "ACCESS_TYPE_REPORT"
	AMFEVENTTYPE_REGISTRATION_STATE_REPORT             string = "REGISTRATION_STATE_REPORT"
	AMFEVENTTYPE_CONNECTIVITY_STATE_REPORT             string = "CONNECTIVITY_STATE_REPORT"
	AMFEVENTTYPE_REACHABILITY_REPORT                   string = "REACHABILITY_REPORT"
	AMFEVENTTYPE_COMMUNICATION_FAILURE_REPORT          string = "COMMUNICATION_FAILURE_REPORT"
	AMFEVENTTYPE_UES_IN_AREA_REPORT                    string = "UES_IN_AREA_REPORT"
	AMFEVENTTYPE_SUBSCRIPTION_ID_CHANGE                string = "SUBSCRIPTION_ID_CHANGE"
	AMFEVENTTYPE_SUBSCRIPTION_ID_ADDITION              string = "SUBSCRIPTION_ID_ADDITION"
	AMFEVENTTYPE_LOSS_OF_CONNECTIVITY                  string = "LOSS_OF_CONNECTIVITY"
	AMFEVENTTYPE_5GS_USER_STATE_REPORT                 string = "5GS_USER_STATE_REPORT"
	AMFEVENTTYPE_AVAILABILITY_AFTER_DDN_FAILURE        string = "AVAILABILITY_AFTER_DDN_FAILURE"
	AMFEVENTTYPE_TYPE_ALLOCATION_CODE_REPORT           string = "TYPE_ALLOCATION_CODE_REPORT"
	AMFEVENTTYPE_FREQUENT_MOBILITY_REGISTRATION_REPORT string = "FREQUENT_MOBILITY_REGISTRATION_REPORT"
	AMFEVENTTYPE_SNSSAI_TA_MAPPING_REPORT              string = "SNSSAI_TA_MAPPING_REPORT"
	AMFEVENTTYPE_UE_LOCATION_TRENDS                    string = "UE_LOCATION_TRENDS"
	AMFEVENTTYPE_UE_ACCESS_BEHAVIOR_TRENDS             string = "UE_ACCESS_BEHAVIOR_TRENDS"
	AMFEVENTTYPE_UE_MM_TRANSACTION_REPORT              string = "UE_MM_TRANSACTION_REPORT"
)
