package models

// Define constant values for AnalyticsMetadata
const (
	ANALYTICSMETADATA_NUM_OF_SAMPLES  string = "NUM_OF_SAMPLES"
	ANALYTICSMETADATA_DATA_WINDOW     string = "DATA_WINDOW"
	ANALYTICSMETADATA_DATA_STAT_PROPS string = "DATA_STAT_PROPS"
	ANALYTICSMETADATA_STRATEGY        string = "STRATEGY"
	ANALYTICSMETADATA_ACCURACY        string = "ACCURACY"
)
