package models

// Define constant values for AnalyticsSubset
const (
	ANALYTICSSUBSET_NUM_OF_UE_REG                             string = "NUM_OF_UE_REG"
	ANALYTICSSUBSET_NUM_OF_PDU_SESS_ESTBL                     string = "NUM_OF_PDU_SESS_ESTBL"
	ANALYTICSSUBSET_RES_USAGE                                 string = "RES_USAGE"
	ANALYTICSSUBSET_NUM_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR    string = "NUM_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR"
	ANALYTICSSUBSET_PERIOD_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR string = "PERIOD_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR"
	ANALYTICSSUBSET_EXCEED_LOAD_LEVEL_THR_IND                 string = "EXCEED_LOAD_LEVEL_THR_IND"
	ANALYTICSSUBSET_LIST_OF_TOP_APP_UL                        string = "LIST_OF_TOP_APP_UL"
	ANALYTICSSUBSET_LIST_OF_TOP_APP_DL                        string = "LIST_OF_TOP_APP_DL"
	ANALYTICSSUBSET_NF_STATUS                                 string = "NF_STATUS"
	ANALYTICSSUBSET_NF_RESOURCE_USAGE                         string = "NF_RESOURCE_USAGE"
	ANALYTICSSUBSET_NF_LOAD                                   string = "NF_LOAD"
	ANALYTICSSUBSET_NF_PEAK_LOAD                              string = "NF_PEAK_LOAD"
	ANALYTICSSUBSET_NF_LOAD_AVG_IN_AOI                        string = "NF_LOAD_AVG_IN_AOI"
	ANALYTICSSUBSET_DISPER_AMOUNT                             string = "DISPER_AMOUNT"
	ANALYTICSSUBSET_DISPER_CLASS                              string = "DISPER_CLASS"
	ANALYTICSSUBSET_RANKING                                   string = "RANKING"
	ANALYTICSSUBSET_PERCENTILE_RANKING                        string = "PERCENTILE_RANKING"
	ANALYTICSSUBSET_RSSI                                      string = "RSSI"
	ANALYTICSSUBSET_RTT                                       string = "RTT"
	ANALYTICSSUBSET_TRAFFIC_INFO                              string = "TRAFFIC_INFO"
	ANALYTICSSUBSET_NUMBER_OF_UES                             string = "NUMBER_OF_UES"
	ANALYTICSSUBSET_APP_LIST_FOR_UE_COMM                      string = "APP_LIST_FOR_UE_COMM"
	ANALYTICSSUBSET_N4_SESS_INACT_TIMER_FOR_UE_COMM           string = "N4_SESS_INACT_TIMER_FOR_UE_COMM"
	ANALYTICSSUBSET_AVG_TRAFFIC_RATE                          string = "AVG_TRAFFIC_RATE"
	ANALYTICSSUBSET_MAX_TRAFFIC_RATE                          string = "MAX_TRAFFIC_RATE"
	ANALYTICSSUBSET_AVG_PACKET_DELAY                          string = "AVG_PACKET_DELAY"
	ANALYTICSSUBSET_MAX_PACKET_DELAY                          string = "MAX_PACKET_DELAY"
	ANALYTICSSUBSET_AVG_PACKET_LOSS_RATE                      string = "AVG_PACKET_LOSS_RATE"
	ANALYTICSSUBSET_UE_LOCATION                               string = "UE_LOCATION"
	ANALYTICSSUBSET_LIST_OF_HIGH_EXP_UE                       string = "LIST_OF_HIGH_EXP_UE"
	ANALYTICSSUBSET_LIST_OF_MEDIUM_EXP_UE                     string = "LIST_OF_MEDIUM_EXP_UE"
	ANALYTICSSUBSET_LIST_OF_LOW_EXP_UE                        string = "LIST_OF_LOW_EXP_UE"
	ANALYTICSSUBSET_AVG_UL_PKT_DROP_RATE                      string = "AVG_UL_PKT_DROP_RATE"
	ANALYTICSSUBSET_VAR_UL_PKT_DROP_RATE                      string = "VAR_UL_PKT_DROP_RATE"
	ANALYTICSSUBSET_AVG_DL_PKT_DROP_RATE                      string = "AVG_DL_PKT_DROP_RATE"
	ANALYTICSSUBSET_VAR_DL_PKT_DROP_RATE                      string = "VAR_DL_PKT_DROP_RATE"
	ANALYTICSSUBSET_AVG_UL_PKT_DELAY                          string = "AVG_UL_PKT_DELAY"
	ANALYTICSSUBSET_VAR_UL_PKT_DELAY                          string = "VAR_UL_PKT_DELAY"
	ANALYTICSSUBSET_AVG_DL_PKT_DELAY                          string = "AVG_DL_PKT_DELAY"
	ANALYTICSSUBSET_VAR_DL_PKT_DELAY                          string = "VAR_DL_PKT_DELAY"
)
