package models
type AuthResult string
// Define constant values for AuthResult
const (
	 AUTHRESULT_AUTHENTICATION_SUCCESS AuthResult = "AUTHENTICATION_SUCCESS"
	 AUTHRESULT_AUTHENTICATION_FAILURE AuthResult = "AUTHENTICATION_FAILURE"
	 AUTHRESULT_AUTHENTICATION_ONGOING AuthResult = "AUTHENTICATION_ONGOING"
) 
