package models

// Define constant values for DispersionOrderingCriterion
const (
	DISPERSIONORDERINGCRITERION_TIME_SLOT_START    string = "TIME_SLOT_START"
	DISPERSIONORDERINGCRITERION_DISPERSION         string = "DISPERSION"
	DISPERSIONORDERINGCRITERION_CLASSIFICATION     string = "CLASSIFICATION"
	DISPERSIONORDERINGCRITERION_RANKING            string = "RANKING"
	DISPERSIONORDERINGCRITERION_PERCENTILE_RANKING string = "PERCENTILE_RANKING"
)
