package models

// Define constant values for DnPerfOrderingCriterion
const (
	DNPERFORDERINGCRITERION_AVERAGE_TRAFFIC_RATE     string = "AVERAGE_TRAFFIC_RATE"
	DNPERFORDERINGCRITERION_MAXIMUM_TRAFFIC_RATE     string = "MAXIMUM_TRAFFIC_RATE"
	DNPERFORDERINGCRITERION_AVERAGE_PACKET_DELAY     string = "AVERAGE_PACKET_DELAY"
	DNPERFORDERINGCRITERION_MAXIMUM_PACKET_DELAY     string = "MAXIMUM_PACKET_DELAY"
	DNPERFORDERINGCRITERION_AVERAGE_PACKET_LOSS_RATE string = "AVERAGE_PACKET_LOSS_RATE"
)
