package models
type EventSubscription struct {
	 NotificationMethod	NotificationMethod	`json:"notificationMethod,omitempty"`
	 RanUeThrouThds	[]string	`json:"ranUeThrouThds,omitempty"`
	 CongThresholds	[]ThresholdLevel	`json:"congThresholds,omitempty"`
	 ExptAnaType	ExpectedAnalyticsType	`json:"exptAnaType,omitempty"`
	 AppServerAddrs	[]AddrFqdn	`json:"appServerAddrs,omitempty"`
	 MatchingDir	MatchingDirection	`json:"matchingDir,omitempty"`
	 ExptUeBehav	*ExpectedUeBehaviourData	`json:"exptUeBehav,omitempty"`
	 AppIds	[]string	`json:"appIds,omitempty"`
	 Dnais	[]string	`json:"dnais,omitempty"`
	 NfInstanceIds	[]string	`json:"nfInstanceIds,omitempty"`
	 MaxTopAppDlNbr	*int	`json:"maxTopAppDlNbr,omitempty"`
	 ExcepRequs	[]Exception	`json:"excepRequs,omitempty"`
	 Dnns	[]string	`json:"dnns,omitempty"`
	 Event	NwdafEvent	`json:"event"`
	 NsiLevelThrds	[]int	`json:"nsiLevelThrds,omitempty"`
	 QosFlowRetThds	[]RetainabilityThreshold	`json:"qosFlowRetThds,omitempty"`
	 DisperReqs	[]DispersionRequirement	`json:"disperReqs,omitempty"`
	 UpfInfo	*UpfInformation	`json:"upfInfo,omitempty"`
	 LadnDnns	[]string	`json:"ladnDnns,omitempty"`
	 LoadLevelThreshold	*int	`json:"loadLevelThreshold,omitempty"`
	 NfLoadLvlThds	[]ThresholdLevel	`json:"nfLoadLvlThds,omitempty"`
	 NfTypes	[]string	`json:"nfTypes,omitempty"`
	 VisitedAreas	[]NetworkAreaInfo	`json:"visitedAreas,omitempty"`
	 TgtUe	*TargetUeInformation	`json:"tgtUe,omitempty"`
	 NfSetIds	[]string	`json:"nfSetIds,omitempty"`
	 MaxTopAppUlNbr	*int	`json:"maxTopAppUlNbr,omitempty"`
	 NsiIdInfos	[]NsiIdInfo	`json:"nsiIdInfos,omitempty"`
	 RatFreqs	[]RatFreqInformation	`json:"ratFreqs,omitempty"`
	 WlanReqs	[]WlanPerformanceReq	`json:"wlanReqs,omitempty"`
	 ExtraReportReq	*EventReportingRequirement	`json:"extraReportReq,omitempty"`
	 NwPerfRequs	[]NetworkPerfRequirement	`json:"nwPerfRequs,omitempty"`
	 BwRequs	[]BwRequirement	`json:"bwRequs,omitempty"`
	 RedTransReqs	[]RedundantTransmissionExpReq	`json:"redTransReqs,omitempty"`
	 DnPerfReqs	[]DnPerformanceReq	`json:"dnPerfReqs,omitempty"`
	 AnySlice	*bool	`json:"anySlice,omitempty"`
	 NetworkArea	*NetworkAreaInfo	`json:"networkArea,omitempty"`
	 QosRequ	*QosRequirement	`json:"qosRequ,omitempty"`
	 RepetitionPeriod	*int	`json:"repetitionPeriod,omitempty"`
	 Snssaia	[]Snssai	`json:"snssaia,omitempty"`
	 ListOfAnaSubsets	[]string	`json:"listOfAnaSubsets,omitempty"`
}
