package models

// Define constant values for ExceptionId
const (
	EXCEPTIONID_UNEXPECTED_UE_LOCATION         string = "UNEXPECTED_UE_LOCATION"
	EXCEPTIONID_UNEXPECTED_LONG_LIVE_FLOW      string = "UNEXPECTED_LONG_LIVE_FLOW"
	EXCEPTIONID_UNEXPECTED_LARGE_RATE_FLOW     string = "UNEXPECTED_LARGE_RATE_FLOW"
	EXCEPTIONID_UNEXPECTED_WAKEUP              string = "UNEXPECTED_WAKEUP"
	EXCEPTIONID_SUSPICION_OF_DDOS_ATTACK       string = "SUSPICION_OF_DDOS_ATTACK"
	EXCEPTIONID_WRONG_DESTINATION_ADDRESS      string = "WRONG_DESTINATION_ADDRESS"
	EXCEPTIONID_TOO_FREQUENT_SERVICE_ACCESS    string = "TOO_FREQUENT_SERVICE_ACCESS"
	EXCEPTIONID_UNEXPECTED_RADIO_LINK_FAILURES string = "UNEXPECTED_RADIO_LINK_FAILURES"
	EXCEPTIONID_PING_PONG_ACROSS_CELLS         string = "PING_PONG_ACROSS_CELLS"
)
