type HsmfUpdateData struct {
	 VcnTunnelInfo	*TunnelInfo	`json:"vcnTunnelInfo,omitempty"`
	 UnknownN1SmInfo	*RefToBinaryData	`json:"unknownN1SmInfo,omitempty"`
	 SupportedFeatures	string	`json:"supportedFeatures,omitempty"`
	 Pei	string	`json:"pei,omitempty"`
	 AdditionalAnType	string	`json:"additionalAnType,omitempty"`
	 UeTimeZone	string	`json:"ueTimeZone,omitempty"`
	 N1SmInfoFromUe	*RefToBinaryData	`json:"n1SmInfoFromUe,omitempty"`
	 UpSecurityInfo	*UpSecurityInfo	`json:"upSecurityInfo,omitempty"`
	 Cause	string	`json:"cause,omitempty"`
	 UnavailableAccessInd	string	`json:"unavailableAccessInd,omitempty"`
	 DnaiList	[]string	`json:"dnaiList,omitempty"`
	 VSmfServiceInstanceId	string	`json:"vSmfServiceInstanceId,omitempty"`
	 HoPreparationIndication	*bool	`json:"hoPreparationIndication,omitempty"`
	 PsaInfo	[]PsaInformation	`json:"psaInfo,omitempty"`
	 AnType	string	`json:"anType,omitempty"`
	 PauseCharging	*bool	`json:"pauseCharging,omitempty"`
	 MaNwUpgradeInd	*bool	`json:"maNwUpgradeInd,omitempty"`
	 IsmfId	string	`json:"ismfId,omitempty"`
	 DlServingPlmnRateCtl	*int	`json:"dlServingPlmnRateCtl,omitempty"`
	 PresenceInLadn	string	`json:"presenceInLadn,omitempty"`
	 SecurityResult	*SecurityResult	`json:"securityResult,omitempty"`
	 UlclBpInfo	*UlclBpInformation	`json:"ulclBpInfo,omitempty"`
	 N4InfoExt2	*N4Information	`json:"n4InfoExt2,omitempty"`
	 VsmfPduSessionUri	string	`json:"vsmfPduSessionUri,omitempty"`
	 EpsInterworkingInd	string	`json:"epsInterworkingInd,omitempty"`
	 ISmfServiceInstanceId	string	`json:"iSmfServiceInstanceId,omitempty"`
	 RoamingChargingProfile	*RoamingChargingProfile	`json:"roamingChargingProfile,omitempty"`
	 VplmnQos	*VplmnQos	`json:"vplmnQos,omitempty"`
	 AdditionalCnTunnelInfo	*TunnelInfo	`json:"additionalCnTunnelInfo,omitempty"`
	 UeLocation	*UserLocation	`json:"ueLocation,omitempty"`
	 SecondaryRatUsageInfo	[]SecondaryRatUsageInfo	`json:"secondaryRatUsageInfo,omitempty"`
	 AmfNfId	string	`json:"amfNfId,omitempty"`
	 SecondaryRatUsageReport	[]SecondaryRatUsageReport	`json:"secondaryRatUsageReport,omitempty"`
	 MaRequestInd	*bool	`json:"maRequestInd,omitempty"`
	 IsmfPduSessionUri	string	`json:"ismfPduSessionUri,omitempty"`
	 QosFlowsRelNotifyList	[]QosFlowItem	`json:"qosFlowsRelNotifyList,omitempty"`
	 EpsBearerId	[]int	`json:"epsBearerId,omitempty"`
	 5gMmCauseValue	*int	`json:"5gMmCauseValue,omitempty"`
	 AnTypeCanBeChanged	*bool	`json:"anTypeCanBeChanged,omitempty"`
	 MaReleaseInd	string	`json:"maReleaseInd,omitempty"`
	 MoExpDataCounter	*MoExpDataCounter	`json:"moExpDataCounter,omitempty"`
	 MaxIntegrityProtectedDataRateUl	string	`json:"maxIntegrityProtectedDataRateUl,omitempty"`
	 IcnTunnelInfo	*TunnelInfo	`json:"icnTunnelInfo,omitempty"`
	 NotifyList	[]PduSessionNotifyItem	`json:"NotifyList,omitempty"`
	 VsmfId	string	`json:"vsmfId,omitempty"`
	 ServingNetwork	*PlmnIdNid	`json:"servingNetwork,omitempty"`
	 RevokeEbiList	[]int	`json:"revokeEbiList,omitempty"`
	 N4Info	*N4Information	`json:"n4Info,omitempty"`
	 UpCnxState	string	`json:"upCnxState,omitempty"`
	 RequestIndication	string	`json:"requestIndication"`
	 RatType	string	`json:"ratType,omitempty"`
	 AddUeLocation	*UserLocation	`json:"addUeLocation,omitempty"`
	 Pti	*int	`json:"pti,omitempty"`
	 AlwaysOnRequested	*bool	`json:"alwaysOnRequested,omitempty"`
	 MaxIntegrityProtectedDataRateDl	string	`json:"maxIntegrityProtectedDataRateDl,omitempty"`
	 QosFlowsNotifyList	[]QosFlowNotifyItem	`json:"qosFlowsNotifyList,omitempty"`
	 NgApCause	*NgApCause	`json:"ngApCause,omitempty"`
	 N4InfoExt1	*N4Information	`json:"n4InfoExt1,omitempty"`
	 Guami	*Guami	`json:"guami,omitempty"`
}
