package models
type ImsVoPs string
// Define constant values for ImsVoPs
const (
	 IMSVOPS_HOMOGENEOUS_SUPPORT ImsVoPs = "HOMOGENEOUS_SUPPORT"
	 IMSVOPS_HOMOGENEOUS_NON_SUPPORT ImsVoPs = "HOMOGENEOUS_NON_SUPPORT"
	 IMSVOPS_NON_HOMOGENEOUS_OR_UNKNOWN ImsVoPs = "NON_HOMOGENEOUS_OR_UNKNOWN"
) 
