package models

type LcsServiceAuth string

// Define constant values for LcsServiceAuth
const (
	LCSSERVICEAUTH_LOCATION_ALLOWED_WITH_NOTIFICATION    LcsServiceAuth = "LOCATION_ALLOWED_WITH_NOTIFICATION"
	LCSSERVICEAUTH_LOCATION_ALLOWED_WITHOUT_NOTIFICATION LcsServiceAuth = "LOCATION_ALLOWED_WITHOUT_NOTIFICATION"
	LCSSERVICEAUTH_LOCATION_ALLOWED_WITHOUT_RESPONSE     LcsServiceAuth = "LOCATION_ALLOWED_WITHOUT_RESPONSE"
	LCSSERVICEAUTH_LOCATION_RESTRICTED_WITHOUT_RESPONSE  LcsServiceAuth = "LOCATION_RESTRICTED_WITHOUT_RESPONSE"
	LCSSERVICEAUTH_NOTIFICATION_ONLY                     LcsServiceAuth = "NOTIFICATION_ONLY"
	LCSSERVICEAUTH_NOTIFICATION_AND_VERIFICATION_ONLY    LcsServiceAuth = "NOTIFICATION_AND_VERIFICATION_ONLY"
)
