type MdtConfiguration struct {
	 CollectionPeriodRmmLte	*string	`json:"collectionPeriodRmmLte,omitempty"`
	 AreaScope	*AreaScope	`json:"areaScope,omitempty"`
	 MeasurementLteList	[]string	`json:"measurementLteList,omitempty"`
	 ReportInterval	*string	`json:"reportInterval,omitempty"`
	 PositioningMethod	*string	`json:"positioningMethod,omitempty"`
	 ReportingTriggerList	[]string	`json:"reportingTriggerList,omitempty"`
	 LoggingDuration	*string	`json:"loggingDuration,omitempty"`
	 AddPositioningMethodList	[]string	`json:"addPositioningMethodList,omitempty"`
	 CollectionPeriodRmmNr	*string	`json:"collectionPeriodRmmNr,omitempty"`
	 MeasurementNrList	[]string	`json:"measurementNrList,omitempty"`
	 SensorMeasurementList	[]string	`json:"sensorMeasurementList,omitempty"`
	 ReportType	*string	`json:"reportType,omitempty"`
	 ReportIntervalNr	*string	`json:"reportIntervalNr,omitempty"`
	 ReportAmount	*string	`json:"reportAmount,omitempty"`
	 JobType	string	`json:"jobType"`
	 EventThresholdRsrqNr	*int	`json:"eventThresholdRsrqNr,omitempty"`
	 LoggingInterval	*string	`json:"loggingInterval,omitempty"`
	 EventThresholdRsrpNr	*int	`json:"eventThresholdRsrpNr,omitempty"`
	 EventThresholdRsrq	*int	`json:"eventThresholdRsrq,omitempty"`
	 MeasurementPeriodLte	*string	`json:"measurementPeriodLte,omitempty"`
	 EventThresholdRsrp	*int	`json:"eventThresholdRsrp,omitempty"`
	 MdtAllowedPlmnIdList	[]PlmnId	`json:"mdtAllowedPlmnIdList,omitempty"`
	 MbsfnAreaList	[]MbsfnArea	`json:"mbsfnAreaList,omitempty"`
	 InterFreqTargetList	[]InterFreqTargetInfo	`json:"interFreqTargetList,omitempty"`
	 EventList	string	`json:"eventList,omitempty"`
	 LoggingIntervalNr	*string	`json:"loggingIntervalNr,omitempty"`
	 LoggingDurationNr	*string	`json:"loggingDurationNr,omitempty"`
}
