package models

// Define constant values for MeasurementNrForMdt
const (
	MEASUREMENTNRFORMDT_M1    string = "M1"
	MEASUREMENTNRFORMDT_M2    string = "M2"
	MEASUREMENTNRFORMDT_M3    string = "M3"
	MEASUREMENTNRFORMDT_M4_DL string = "M4_DL"
	MEASUREMENTNRFORMDT_M4_UL string = "M4_UL"
	MEASUREMENTNRFORMDT_M5_DL string = "M5_DL"
	MEASUREMENTNRFORMDT_M5_UL string = "M5_UL"
	MEASUREMENTNRFORMDT_M6_DL string = "M6_DL"
	MEASUREMENTNRFORMDT_M6_UL string = "M6_UL"
	MEASUREMENTNRFORMDT_M7_DL string = "M7_DL"
	MEASUREMENTNRFORMDT_M7_UL string = "M7_UL"
	MEASUREMENTNRFORMDT_M8    string = "M8"
	MEASUREMENTNRFORMDT_M9    string = "M9"
)
