package models

// Define constant values for MeasurementLteForMdt
const (
	MEASUREMENTLTEFORMDT_M1    string = "M1"
	MEASUREMENTLTEFORMDT_M2    string = "M2"
	MEASUREMENTLTEFORMDT_M3    string = "M3"
	MEASUREMENTLTEFORMDT_M4_DL string = "M4_DL"
	MEASUREMENTLTEFORMDT_M4_UL string = "M4_UL"
	MEASUREMENTLTEFORMDT_M5_DL string = "M5_DL"
	MEASUREMENTLTEFORMDT_M5_UL string = "M5_UL"
	MEASUREMENTLTEFORMDT_M6_DL string = "M6_DL"
	MEASUREMENTLTEFORMDT_M6_UL string = "M6_UL"
	MEASUREMENTLTEFORMDT_M7_DL string = "M7_DL"
	MEASUREMENTLTEFORMDT_M7_UL string = "M7_UL"
	MEASUREMENTLTEFORMDT_M8    string = "M8"
	MEASUREMENTLTEFORMDT_M9    string = "M9"
)
