package models

// Define constant values for N1N2MessageTransferCause
const (
	N1N2MESSAGETRANSFERCAUSE_ATTEMPTING_TO_REACH_UE                string = "ATTEMPTING_TO_REACH_UE"
	N1N2MESSAGETRANSFERCAUSE_N1_N2_TRANSFER_INITIATED              string = "N1_N2_TRANSFER_INITIATED"
	N1N2MESSAGETRANSFERCAUSE_WAITING_FOR_ASYNCHRONOUS_TRANSFER     string = "WAITING_FOR_ASYNCHRONOUS_TRANSFER"
	N1N2MESSAGETRANSFERCAUSE_UE_NOT_RESPONDING                     string = "UE_NOT_RESPONDING"
	N1N2MESSAGETRANSFERCAUSE_N1_MSG_NOT_TRANSFERRED                string = "N1_MSG_NOT_TRANSFERRED"
	N1N2MESSAGETRANSFERCAUSE_N2_MSG_NOT_TRANSFERRED                string = "N2_MSG_NOT_TRANSFERRED"
	N1N2MESSAGETRANSFERCAUSE_UE_NOT_REACHABLE_FOR_SESSION          string = "UE_NOT_REACHABLE_FOR_SESSION"
	N1N2MESSAGETRANSFERCAUSE_TEMPORARY_REJECT_REGISTRATION_ONGOING string = "TEMPORARY_REJECT_REGISTRATION_ONGOING"
	N1N2MESSAGETRANSFERCAUSE_TEMPORARY_REJECT_HANDOVER_ONGOING     string = "TEMPORARY_REJECT_HANDOVER_ONGOING"
	N1N2MESSAGETRANSFERCAUSE_REJECTION_DUE_TO_PAGING_RESTRICTION   string = "REJECTION_DUE_TO_PAGING_RESTRICTION"
	N1N2MESSAGETRANSFERCAUSE_AN_NOT_RESPONDING                     string = "AN_NOT_RESPONDING"
	N1N2MESSAGETRANSFERCAUSE_FAILURE_CAUSE_UNSPECIFIED             string = "FAILURE_CAUSE_UNSPECIFIED"
)
