package models

// Define constant values for N4MessageType
const (
	N4MESSAGETYPE_PFCP_SES_EST_REQ string = "PFCP_SES_EST_REQ"
	N4MESSAGETYPE_PFCP_SES_EST_RSP string = "PFCP_SES_EST_RSP"
	N4MESSAGETYPE_PFCP_SES_MOD_REQ string = "PFCP_SES_MOD_REQ"
	N4MESSAGETYPE_PFCP_SES_MOD_RSP string = "PFCP_SES_MOD_RSP"
	N4MESSAGETYPE_PFCP_SES_DEL_REQ string = "PFCP_SES_DEL_REQ"
	N4MESSAGETYPE_PFCP_SES_DEL_RSP string = "PFCP_SES_DEL_RSP"
	N4MESSAGETYPE_PFCP_SES_REP_REQ string = "PFCP_SES_REP_REQ"
	N4MESSAGETYPE_PFCP_SES_REP_RSP string = "PFCP_SES_REP_RSP"
)
