package models

// Define constant values for NetworkPerfType
const (
	NETWORKPERFTYPE_GNB_ACTIVE_RATIO    string = "GNB_ACTIVE_RATIO"
	NETWORKPERFTYPE_GNB_COMPUTING_USAGE string = "GNB_COMPUTING_USAGE"
	NETWORKPERFTYPE_GNB_MEMORY_USAGE    string = "GNB_MEMORY_USAGE"
	NETWORKPERFTYPE_GNB_DISK_USAGE      string = "GNB_DISK_USAGE"
	NETWORKPERFTYPE_NUM_OF_UE           string = "NUM_OF_UE"
	NETWORKPERFTYPE_SESS_SUCC_RATIO     string = "SESS_SUCC_RATIO"
	NETWORKPERFTYPE_HO_SUCC_RATIO       string = "HO_SUCC_RATIO"
)
