package models

// Define constant values for NgapIeType
const (
	NGAPIETYPE_PDU_RES_SETUP_REQ              string = "PDU_RES_SETUP_REQ"
	NGAPIETYPE_PDU_RES_REL_CMD                string = "PDU_RES_REL_CMD"
	NGAPIETYPE_PDU_RES_MOD_REQ                string = "PDU_RES_MOD_REQ"
	NGAPIETYPE_HANDOVER_CMD                   string = "HANDOVER_CMD"
	NGAPIETYPE_HANDOVER_REQUIRED              string = "HANDOVER_REQUIRED"
	NGAPIETYPE_HANDOVER_PREP_FAIL             string = "HANDOVER_PREP_FAIL"
	NGAPIETYPE_SRC_TO_TAR_CONTAINER           string = "SRC_TO_TAR_CONTAINER"
	NGAPIETYPE_TAR_TO_SRC_CONTAINER           string = "TAR_TO_SRC_CONTAINER"
	NGAPIETYPE_TAR_TO_SRC_FAIL_CONTAINER      string = "TAR_TO_SRC_FAIL_CONTAINER"
	NGAPIETYPE_RAN_STATUS_TRANS_CONTAINER     string = "RAN_STATUS_TRANS_CONTAINER"
	NGAPIETYPE_SON_CONFIG_TRANSFER            string = "SON_CONFIG_TRANSFER"
	NGAPIETYPE_NRPPA_PDU                      string = "NRPPA_PDU"
	NGAPIETYPE_UE_RADIO_CAPABILITY            string = "UE_RADIO_CAPABILITY"
	NGAPIETYPE_RIM_INFO_TRANSFER              string = "RIM_INFO_TRANSFER"
	NGAPIETYPE_SECONDARY_RAT_USAGE            string = "SECONDARY_RAT_USAGE"
	NGAPIETYPE_PC5_QOS_PARA                   string = "PC5_QOS_PARA"
	NGAPIETYPE_EARLY_STATUS_TRANS_CONTAINER   string = "EARLY_STATUS_TRANS_CONTAINER"
	NGAPIETYPE_UE_RADIO_CAPABILITY_FOR_PAGING string = "UE_RADIO_CAPABILITY_FOR_PAGING"
)
