package models

// Define constant values for NotificationCause
const (
	NOTIFICATIONCAUSE_QOS_FULFILLED        string = "QOS_FULFILLED"
	NOTIFICATIONCAUSE_QOS_NOT_FULFILLED    string = "QOS_NOT_FULFILLED"
	NOTIFICATIONCAUSE_UP_SEC_FULFILLED     string = "UP_SEC_FULFILLED"
	NOTIFICATIONCAUSE_UP_SEC_NOT_FULFILLED string = "UP_SEC_NOT_FULFILLED"
)
