package models

// Define constant values for NwdafEvent
const (
	NWDAFEVENT_SLICE_LOAD_LEVEL     string = "SLICE_LOAD_LEVEL"
	NWDAFEVENT_NETWORK_PERFORMANCE  string = "NETWORK_PERFORMANCE"
	NWDAFEVENT_NF_LOAD              string = "NF_LOAD"
	NWDAFEVENT_SERVICE_EXPERIENCE   string = "SERVICE_EXPERIENCE"
	NWDAFEVENT_UE_MOBILITY          string = "UE_MOBILITY"
	NWDAFEVENT_UE_COMMUNICATION     string = "UE_COMMUNICATION"
	NWDAFEVENT_QOS_SUSTAINABILITY   string = "QOS_SUSTAINABILITY"
	NWDAFEVENT_ABNORMAL_BEHAVIOUR   string = "ABNORMAL_BEHAVIOUR"
	NWDAFEVENT_USER_DATA_CONGESTION string = "USER_DATA_CONGESTION"
	NWDAFEVENT_NSI_LOAD_LEVEL       string = "NSI_LOAD_LEVEL"
	NWDAFEVENT_DN_PERFORMANCE       string = "DN_PERFORMANCE"
	NWDAFEVENT_DISPERSION           string = "DISPERSION"
	NWDAFEVENT_RED_TRANS_EXP        string = "RED_TRANS_EXP"
	NWDAFEVENT_WLAN_PERFORMANCE     string = "WLAN_PERFORMANCE"
	NWDAFEVENT_SM_CONGESTION        string = "SM_CONGESTION"
)
