package models

type PduSessionCreateData struct {
	Dnn                             string                          `json:"dnn"`
	SNssai                          *Snssai                         `json:"sNssai,omitempty"`
	N9ForwardingTunnelInfo          *TunnelInfo                     `json:"n9ForwardingTunnelInfo,omitempty"`
	UeTimeZone                      string                          `json:"ueTimeZone,omitempty"`
	Gpsi                            string                          `json:"gpsi,omitempty"`
	UnknownN1SmInfo                 *RefToBinaryData                `json:"unknownN1SmInfo,omitempty"`
	MaxIntegrityProtectedDataRateDl MaxIntegrityProtectedDataRate   `json:"maxIntegrityProtectedDataRateDl,omitempty"`
	IsmfId                          string                          `json:"ismfId,omitempty"`
	PcfId                           string                          `json:"pcfId,omitempty"`
	PcfGroupId                      string                          `json:"pcfGroupId,omitempty"`
	PcfSetId                        string                          `json:"pcfSetId,omitempty"`
	AmfNfId                         string                          `json:"amfNfId,omitempty"`
	InvokeNef                       *bool                           `json:"invokeNef,omitempty"`
	SmallDataRateStatus             *SmallDataRateStatus            `json:"smallDataRateStatus,omitempty"`
	DlServingPlmnRateCtl            *int                            `json:"dlServingPlmnRateCtl,omitempty"`
	OldSmContextRef                 string                          `json:"oldSmContextRef,omitempty"`
	PgwS8cFteid                     string                          `json:"pgwS8cFteid,omitempty"`
	VsmfPduSessionUri               string                          `json:"vsmfPduSessionUri,omitempty"`
	AdditionalCnTunnelInfo          *TunnelInfo                     `json:"additionalCnTunnelInfo,omitempty"`
	RoamingChargingProfile          *RoamingChargingProfile         `json:"roamingChargingProfile,omitempty"`
	EpsBearerCtxStatus              string                          `json:"epsBearerCtxStatus,omitempty"`
	CpOnlyInd                       *bool                           `json:"cpOnlyInd,omitempty"`
	SatelliteBackhaulCat            SatelliteBackhaulCategory       `json:"satelliteBackhaulCat,omitempty"`
	UpipSupported                   *bool                           `json:"upipSupported,omitempty"`
	VsmfId                          string                          `json:"vsmfId,omitempty"`
	AdditionalAnType                AccessType                      `json:"additionalAnType,omitempty"`
	AddUeLocation                   *UserLocation                   `json:"addUeLocation,omitempty"`
	MaxIntegrityProtectedDataRateUl MaxIntegrityProtectedDataRate   `json:"maxIntegrityProtectedDataRateUl,omitempty"`
	MaRequestInd                    *bool                           `json:"maRequestInd,omitempty"`
	VplmnQos                        *VplmnQos                       `json:"vplmnQos,omitempty"`
	AnType                          AccessType                      `json:"anType"`
	RoutingIndicator                string                          `json:"routingIndicator,omitempty"`
	SmPolicyNotifyInd               *bool                           `json:"smPolicyNotifyInd,omitempty"`
	PcfUeCallbackInfo               *PcfUeCallbackInfo              `json:"pcfUeCallbackInfo,omitempty"`
	UnauthenticatedSupi             *bool                           `json:"unauthenticatedSupi,omitempty"`
	EpsBearerId                     []int                           `json:"epsBearerId,omitempty"`
	HoPreparationIndication         *bool                           `json:"hoPreparationIndication,omitempty"`
	ISmfServiceInstanceId           string                          `json:"iSmfServiceInstanceId,omitempty"`
	OldPduSessionId                 *int                            `json:"oldPduSessionId,omitempty"`
	SecondaryRatUsageInfo           []SecondaryRatUsageInfo         `json:"secondaryRatUsageInfo,omitempty"`
	UdmGroupId                      string                          `json:"udmGroupId,omitempty"`
	ChargingId                      string                          `json:"chargingId,omitempty"`
	CpCiotEnabled                   *bool                           `json:"cpCiotEnabled,omitempty"`
	DnaiList                        []string                        `json:"dnaiList,omitempty"`
	RequestType                     RequestType                     `json:"requestType,omitempty"`
	Guami                           *Guami                          `json:"guami,omitempty"`
	PresenceInLadn                  PresenceState                   `json:"presenceInLadn,omitempty"`
	IsmfPduSessionUri               string                          `json:"ismfPduSessionUri,omitempty"`
	UeLocation                      *UserLocation                   `json:"ueLocation,omitempty"`
	HPcfId                          string                          `json:"hPcfId,omitempty"`
	OldPduSessionRef                string                          `json:"oldPduSessionRef,omitempty"`
	DisasterRoamingInd              *bool                           `json:"disasterRoamingInd,omitempty"`
	SelectedDnn                     string                          `json:"selectedDnn,omitempty"`
	AlwaysOnRequested               *bool                           `json:"alwaysOnRequested,omitempty"`
	Supi                            string                          `json:"supi,omitempty"`
	VcnTunnelInfo                   *TunnelInfo                     `json:"vcnTunnelInfo,omitempty"`
	SupportedFeatures               string                          `json:"supportedFeatures,omitempty"`
	SelMode                         DnnSelectionMode                `json:"selMode,omitempty"`
	RecoveryTime                    string                          `json:"recoveryTime,omitempty"`
	UpSecurityInfo                  *UpSecurityInfo                 `json:"upSecurityInfo,omitempty"`
	RedundantPduSessionInfo         *RedundantPduSessionInformation `json:"redundantPduSessionInfo,omitempty"`
	PduSessionId                    *int                            `json:"pduSessionId,omitempty"`
	HplmnSnssai                     *Snssai                         `json:"hplmnSnssai,omitempty"`
	IcnTunnelInfo                   *TunnelInfo                     `json:"icnTunnelInfo,omitempty"`
	HNwPubKeyId                     *int                            `json:"hNwPubKeyId,omitempty"`
	N1SmInfoFromUe                  *RefToBinaryData                `json:"n1SmInfoFromUe,omitempty"`
	Pei                             string                          `json:"pei,omitempty"`
	EpsInterworkingInd              EpsInterworkingIndication       `json:"epsInterworkingInd,omitempty"`
	ApnRateStatus                   *ApnRateStatus                  `json:"apnRateStatus,omitempty"`
	UpCnxState                      UpCnxState                      `json:"upCnxState,omitempty"`
	ServingNetwork                  PlmnIdNid                       `json:"servingNetwork"`
	RatType                         RatType                         `json:"ratType,omitempty"`
	VSmfServiceInstanceId           string                          `json:"vSmfServiceInstanceId,omitempty"`
	MaNwUpgradeInd                  *bool                           `json:"maNwUpgradeInd,omitempty"`
}
