type PduSessionCreatedData struct {
	 HcnTunnelInfo	*TunnelInfo	`json:"hcnTunnelInfo,omitempty"`
	 EpsPdnCnxInfo	*EpsPdnCnxInfo	`json:"epsPdnCnxInfo,omitempty"`
	 DnaiList	[]string	`json:"dnaiList,omitempty"`
	 Ipv6MultiHomingInd	*bool	`json:"ipv6MultiHomingInd,omitempty"`
	 CnTunnelInfo	*TunnelInfo	`json:"cnTunnelInfo,omitempty"`
	 EnablePauseCharging	*bool	`json:"enablePauseCharging,omitempty"`
	 UeIpv4Address	string	`json:"ueIpv4Address,omitempty"`
	 Gpsi	string	`json:"gpsi,omitempty"`
	 RedundantPduSessionInfo	*RedundantPduSessionInformation	`json:"redundantPduSessionInfo,omitempty"`
	 HSmfInstanceId	string	`json:"hSmfInstanceId,omitempty"`
	 SNssai	*Snssai	`json:"sNssai,omitempty"`
	 SupportedFeatures	string	`json:"supportedFeatures,omitempty"`
	 SessionAmbr	*Ambr	`json:"sessionAmbr,omitempty"`
	 PduSessionId	*int	`json:"pduSessionId,omitempty"`
	 UeIpv6Prefix	string	`json:"ueIpv6Prefix,omitempty"`
	 N1SmInfoToUe	*RefToBinaryData	`json:"n1SmInfoToUe,omitempty"`
	 UpSecurity	*UpSecurity	`json:"upSecurity,omitempty"`
	 UeIpv6InterfaceId	string	`json:"ueIpv6InterfaceId,omitempty"`
	 HSmfServiceInstanceId	string	`json:"hSmfServiceInstanceId,omitempty"`
	 HomeProvidedChargingId	string	`json:"homeProvidedChargingId,omitempty"`
	 Ipv6Index	*int	`json:"ipv6Index,omitempty"`
	 QosFlowsSetupList	[]QosFlowSetupItem	`json:"qosFlowsSetupList,omitempty"`
	 MaxIntegrityProtectedDataRate	string	`json:"maxIntegrityProtectedDataRate,omitempty"`
	 AlwaysOnGranted	*bool	`json:"alwaysOnGranted,omitempty"`
	 SmallDataRateControlEnabled	*bool	`json:"smallDataRateControlEnabled,omitempty"`
	 DnAaaAddress	*IpAddress	`json:"dnAaaAddress,omitempty"`
	 SscMode	string	`json:"sscMode"`
	 SmfInstanceId	string	`json:"smfInstanceId,omitempty"`
	 MaxIntegrityProtectedDataRateDl	string	`json:"maxIntegrityProtectedDataRateDl,omitempty"`
	 SmfServiceInstanceId	string	`json:"smfServiceInstanceId,omitempty"`
	 MaAcceptedInd	*bool	`json:"maAcceptedInd,omitempty"`
	 NefExtBufSupportInd	*bool	`json:"nefExtBufSupportInd,omitempty"`
	 PduSessionType	string	`json:"pduSessionType"`
	 AdditionalCnTunnelInfo	*TunnelInfo	`json:"additionalCnTunnelInfo,omitempty"`
	 EpsBearerInfo	[]EpsBearerInfo	`json:"epsBearerInfo,omitempty"`
	 RoamingChargingProfile	*RoamingChargingProfile	`json:"roamingChargingProfile,omitempty"`
	 RecoveryTime	string	`json:"recoveryTime,omitempty"`
}
