package models
type PolicyDecisionFailureCode string
// Define constant values for PolicyDecisionFailureCode
const (
	 POLICYDECISIONFAILURECODE_TRA_CTRL_DECS_ERR PolicyDecisionFailureCode = "TRA_CTRL_DECS_ERR"
	 POLICYDECISIONFAILURECODE_QOS_DECS_ERR PolicyDecisionFailureCode = "QOS_DECS_ERR"
	 POLICYDECISIONFAILURECODE_CHG_DECS_ERR PolicyDecisionFailureCode = "CHG_DECS_ERR"
	 POLICYDECISIONFAILURECODE_USA_MON_DECS_ERR PolicyDecisionFailureCode = "USA_MON_DECS_ERR"
	 POLICYDECISIONFAILURECODE_QOS_MON_DECS_ERR PolicyDecisionFailureCode = "QOS_MON_DECS_ERR"
	 POLICYDECISIONFAILURECODE_CON_DATA_ERR PolicyDecisionFailureCode = "CON_DATA_ERR"
	 POLICYDECISIONFAILURECODE_POLICY_PARAM_ERR PolicyDecisionFailureCode = "POLICY_PARAM_ERR"
) 
