package models

// Define constant values for PolicyReqTrigger
const (
	POLICYREQTRIGGER_LOCATION_CHANGE      string = "LOCATION_CHANGE"
	POLICYREQTRIGGER_PRA_CHANGE           string = "PRA_CHANGE"
	POLICYREQTRIGGER_ALLOWED_NSSAI_CHANGE string = "ALLOWED_NSSAI_CHANGE"
	POLICYREQTRIGGER_NWDAF_DATA_CHANGE    string = "NWDAF_DATA_CHANGE"
	POLICYREQTRIGGER_PLMN_CHANGE          string = "PLMN_CHANGE"
	POLICYREQTRIGGER_CON_STATE_CHANGE     string = "CON_STATE_CHANGE"
	POLICYREQTRIGGER_SMF_SELECT_CHANGE    string = "SMF_SELECT_CHANGE"
	POLICYREQTRIGGER_ACCESS_TYPE_CHANGE   string = "ACCESS_TYPE_CHANGE"
)
