package models

// Define constant values for RatType
const (
	RATTYPE_NR                  string = "NR"
	RATTYPE_EUTRA               string = "EUTRA"
	RATTYPE_WLAN                string = "WLAN"
	RATTYPE_VIRTUAL             string = "VIRTUAL"
	RATTYPE_NBIOT               string = "NBIOT"
	RATTYPE_WIRELINE            string = "WIRELINE"
	RATTYPE_WIRELINE_CABLE      string = "WIRELINE_CABLE"
	RATTYPE_WIRELINE_BBF        string = "WIRELINE_BBF"
	RATTYPE_LTE_M               string = "LTE-M"
	RATTYPE_NR_U                string = "NR_U"
	RATTYPE_EUTRA_U             string = "EUTRA_U"
	RATTYPE_TRUSTED_N3GA        string = "TRUSTED_N3GA"
	RATTYPE_TRUSTED_WLAN        string = "TRUSTED_WLAN"
	RATTYPE_UTRA                string = "UTRA"
	RATTYPE_GERA                string = "GERA"
	RATTYPE_NR_LEO              string = "NR_LEO"
	RATTYPE_NR_MEO              string = "NR_MEO"
	RATTYPE_NR_GEO              string = "NR_GEO"
	RATTYPE_NR_OTHER_SAT        string = "NR_OTHER_SAT"
	RATTYPE_NR_REDCAP           string = "NR_REDCAP"
	RATTYPE_WB_E_UTRAN_LEO      string = "WB_E_UTRAN_LEO"
	RATTYPE_WB_E_UTRAN_MEO      string = "WB_E_UTRAN_MEO"
	RATTYPE_WB_E_UTRAN_GEO      string = "WB_E_UTRAN_GEO"
	RATTYPE_WB_E_UTRAN_OTHERSAT string = "WB_E_UTRAN_OTHERSAT"
	RATTYPE_NB_IOT_LEO          string = "NB_IOT_LEO"
	RATTYPE_NB_IOT_MEO          string = "NB_IOT_MEO"
	RATTYPE_NB_IOT_GEO          string = "NB_IOT_GEO"
	RATTYPE_NB_IOT_OTHERSAT     string = "NB_IOT_OTHERSAT"
	RATTYPE_LTE_M_LEO           string = "LTE_M_LEO"
	RATTYPE_LTE_M_MEO           string = "LTE_M_MEO"
	RATTYPE_LTE_M_GEO           string = "LTE_M_GEO"
	RATTYPE_LTE_M_OTHERSAT      string = "LTE_M_OTHERSAT"
)
