package models

// Define constant values for RequestType
const (
	REQUESTTYPE_INITIAL_REQUEST                string = "INITIAL_REQUEST"
	REQUESTTYPE_EXISTING_PDU_SESSION           string = "EXISTING_PDU_SESSION"
	REQUESTTYPE_INITIAL_EMERGENCY_REQUEST      string = "INITIAL_EMERGENCY_REQUEST"
	REQUESTTYPE_EXISTING_EMERGENCY_PDU_SESSION string = "EXISTING_EMERGENCY_PDU_SESSION"
)
