package models

// Define constant values for RequestIndication
const (
	REQUESTINDICATION_UE_REQ_PDU_SES_MOD       string = "UE_REQ_PDU_SES_MOD"
	REQUESTINDICATION_UE_REQ_PDU_SES_REL       string = "UE_REQ_PDU_SES_REL"
	REQUESTINDICATION_PDU_SES_MOB              string = "PDU_SES_MOB"
	REQUESTINDICATION_NW_REQ_PDU_SES_AUTH      string = "NW_REQ_PDU_SES_AUTH"
	REQUESTINDICATION_NW_REQ_PDU_SES_MOD       string = "NW_REQ_PDU_SES_MOD"
	REQUESTINDICATION_NW_REQ_PDU_SES_REL       string = "NW_REQ_PDU_SES_REL"
	REQUESTINDICATION_EBI_ASSIGNMENT_REQ       string = "EBI_ASSIGNMENT_REQ"
	REQUESTINDICATION_REL_DUE_TO_5G_AN_REQUEST string = "REL_DUE_TO_5G_AN_REQUEST"
)
