package models

// Define constant values for SbiBindingLevel
const (
	SBIBINDINGLEVEL_NF_INSTANCE_BINDING         string = "NF_INSTANCE_BINDING"
	SBIBINDINGLEVEL_NF_SET_BINDING              string = "NF_SET_BINDING"
	SBIBINDINGLEVEL_NF_SERVICE_SET_BINDING      string = "NF_SERVICE_SET_BINDING"
	SBIBINDINGLEVEL_NF_SERVICE_INSTANCE_BINDING string = "NF_SERVICE_INSTANCE_BINDING"
)
