package models

// Define constant values for ScheduledCommunicationType
const (
	SCHEDULEDCOMMUNICATIONTYPE_DOWNLINK_ONLY string = "DOWNLINK_ONLY"
	SCHEDULEDCOMMUNICATIONTYPE_UPLINK_ONLY   string = "UPLINK_ONLY"
	SCHEDULEDCOMMUNICATIONTYPE_BIDIRECTIONAL string = "BIDIRECTIONAL"
)
