type SmContextUpdateData struct {
	 RatType	string	`json:"ratType,omitempty"`
	 N2SmInfo	*RefToBinaryData	`json:"n2SmInfo,omitempty"`
	 TargetId	*NgRanTargetId	`json:"targetId,omitempty"`
	 N9ForwardingTunnel	*TunnelInfo	`json:"n9ForwardingTunnel,omitempty"`
	 N9DlForwardingTnlList	[]IndirectDataForwardingTunnelInfo	`json:"n9DlForwardingTnlList,omitempty"`
	 AnTypeCanBeChanged	*bool	`json:"anTypeCanBeChanged,omitempty"`
	 ForwardingBearerContexts	[]string	`json:"forwardingBearerContexts,omitempty"`
	 ServingNfId	string	`json:"servingNfId,omitempty"`
	 AnTypeToReactivate	string	`json:"anTypeToReactivate,omitempty"`
	 Cause	string	`json:"cause,omitempty"`
	 5gMmCauseValue	*int	`json:"5gMmCauseValue,omitempty"`
	 Pei	string	`json:"pei,omitempty"`
	 HoState	string	`json:"hoState,omitempty"`
	 ToBeSwitched	*bool	`json:"toBeSwitched,omitempty"`
	 TargetServingNfId	string	`json:"targetServingNfId,omitempty"`
	 Guami	*Guami	`json:"guami,omitempty"`
	 Release	*bool	`json:"release,omitempty"`
	 NgApCause	*NgApCause	`json:"ngApCause,omitempty"`
	 EpsInterworkingInd	string	`json:"epsInterworkingInd,omitempty"`
	 N2SmInfoTypeExt1	string	`json:"n2SmInfoTypeExt1,omitempty"`
	 SmContextStatusUri	string	`json:"smContextStatusUri,omitempty"`
	 FailedToBeSwitched	*bool	`json:"failedToBeSwitched,omitempty"`
	 N2SmInfoType	string	`json:"n2SmInfoType,omitempty"`
	 EpsBearerSetup	[]string	`json:"epsBearerSetup,omitempty"`
	 MaReleaseInd	string	`json:"maReleaseInd,omitempty"`
	 MaNwUpgradeInd	*bool	`json:"maNwUpgradeInd,omitempty"`
	 MoExpDataCounter	*MoExpDataCounter	`json:"moExpDataCounter,omitempty"`
	 ExtendedNasSmTimerInd	*bool	`json:"extendedNasSmTimerInd,omitempty"`
	 AnType	string	`json:"anType,omitempty"`
	 ForwardingFTeid	string	`json:"forwardingFTeid,omitempty"`
	 UeLocation	*UserLocation	`json:"ueLocation,omitempty"`
	 UeTimeZone	string	`json:"ueTimeZone,omitempty"`
	 N1SmMsg	*RefToBinaryData	`json:"n1SmMsg,omitempty"`
	 DdnFailureSubs	*DdnFailureSubs	`json:"ddnFailureSubs,omitempty"`
	 SkipN2PduSessionResRelInd	*bool	`json:"skipN2PduSessionResRelInd,omitempty"`
	 ServingNetwork	*PlmnIdNid	`json:"servingNetwork,omitempty"`
	 RevokeEbiList	[]int	`json:"revokeEbiList,omitempty"`
	 SNssai	*Snssai	`json:"sNssai,omitempty"`
	 TraceData	*TraceData	`json:"traceData,omitempty"`
	 N2SmInfoExt1	*RefToBinaryData	`json:"n2SmInfoExt1,omitempty"`
	 MaRequestInd	*bool	`json:"maRequestInd,omitempty"`
	 N9UlForwardingTnlList	[]IndirectDataForwardingTunnelInfo	`json:"n9UlForwardingTnlList,omitempty"`
	 AdditionalAnType	string	`json:"additionalAnType,omitempty"`
	 PresenceInLadn	string	`json:"presenceInLadn,omitempty"`
	 AddUeLocation	*UserLocation	`json:"addUeLocation,omitempty"`
	 UpCnxState	string	`json:"upCnxState,omitempty"`
	 DataForwarding	*bool	`json:"dataForwarding,omitempty"`
	 ExemptionInd	*ExemptionInd	`json:"exemptionInd,omitempty"`
	 SupportedFeatures	string	`json:"supportedFeatures,omitempty"`
	 BackupAmfInfo	[]BackupAmfInfo	`json:"backupAmfInfo,omitempty"`
}
