package models

type SmContextCreateData struct {
	PcfId                      string                    `json:"pcfId,omitempty"`
	SmfBindingInfo             string                    `json:"smfBindingInfo,omitempty"`
	PcfUeCallbackInfo          *PcfUeCallbackInfo        `json:"pcfUeCallbackInfo,omitempty"`
	UnauthenticatedSupi        *bool                     `json:"unauthenticatedSupi,omitempty"`
	HSmfUri                    string                    `json:"hSmfUri,omitempty"`
	RequestType                RequestType               `json:"requestType,omitempty"`
	PresenceInLadn             PresenceState             `json:"presenceInLadn,omitempty"`
	UeEpsPdnConnection         string                    `json:"ueEpsPdnConnection,omitempty"`
	PcfSetId                   string                    `json:"pcfSetId,omitempty"`
	N2SmInfoExt1               *RefToBinaryData          `json:"n2SmInfoExt1,omitempty"`
	TwifInfo                   *TwifInfo                 `json:"twifInfo,omitempty"`
	Pei                        string                    `json:"pei,omitempty"`
	Guami                      *Guami                    `json:"guami,omitempty"`
	HoState                    HoState                   `json:"hoState,omitempty"`
	CpOnlyInd                  *bool                     `json:"cpOnlyInd,omitempty"`
	SmContextSmfBinding        SbiBindingLevel           `json:"smContextSmfBinding,omitempty"`
	DlDataWaitingInd           *bool                     `json:"dlDataWaitingInd,omitempty"`
	UavAuthenticated           *bool                     `json:"uavAuthenticated,omitempty"`
	ServingNetwork             PlmnIdNid                 `json:"servingNetwork"`
	AnType                     AccessType                `json:"anType"`
	EpsBearerCtxStatus         string                    `json:"epsBearerCtxStatus,omitempty"`
	SmallDataRateStatus        *SmallDataRateStatus      `json:"smallDataRateStatus,omitempty"`
	NrfDiscoveryUri            string                    `json:"nrfDiscoveryUri,omitempty"`
	PcfGroupId                 string                    `json:"pcfGroupId,omitempty"`
	IndirectForwardingFlag     *bool                     `json:"indirectForwardingFlag,omitempty"`
	UdmGroupId                 string                    `json:"udmGroupId,omitempty"`
	ApnRateStatus              *ApnRateStatus            `json:"apnRateStatus,omitempty"`
	PvsInfo                    []ServerAddressingInfo    `json:"pvsInfo,omitempty"`
	OnboardingInd              *bool                     `json:"onboardingInd,omitempty"`
	AnchorSmfOauth2Required    *bool                     `json:"anchorSmfOauth2Required,omitempty"`
	AdditionalHsmfUri          []string                  `json:"additionalHsmfUri,omitempty"`
	PduSessionsActivateList    []int                     `json:"pduSessionsActivateList,omitempty"`
	MaRequestInd               *bool                     `json:"maRequestInd,omitempty"`
	MaNwUpgradeInd             *bool                     `json:"maNwUpgradeInd,omitempty"`
	N2SmInfo                   *RefToBinaryData          `json:"n2SmInfo,omitempty"`
	UpCnxState                 UpCnxState                `json:"upCnxState,omitempty"`
	DdnFailureSubs             *DdnFailureSubs           `json:"ddnFailureSubs,omitempty"`
	SmContextStatusUri         string                    `json:"smContextStatusUri"`
	BackupAmfInfo              []BackupAmfInfo           `json:"backupAmfInfo,omitempty"`
	InvokeNef                  *bool                     `json:"invokeNef,omitempty"`
	N2SmInfoTypeExt1           N2SmInfoType              `json:"n2SmInfoTypeExt1,omitempty"`
	SmContextSmfSetId          string                    `json:"smContextSmfSetId,omitempty"`
	RanUnchangedInd            *bool                     `json:"ranUnchangedInd,omitempty"`
	SatelliteBackhaulCat       SatelliteBackhaulCategory `json:"satelliteBackhaulCat,omitempty"`
	ServingNfId                string                    `json:"servingNfId"`
	TargetId                   *NgRanTargetId            `json:"targetId,omitempty"`
	AdditionalHsmfId           []string                  `json:"additionalHsmfId,omitempty"`
	SupportedFeatures          string                    `json:"supportedFeatures,omitempty"`
	SelMode                    DnnSelectionMode          `json:"selMode,omitempty"`
	EpsInterworkingInd         EpsInterworkingIndication `json:"epsInterworkingInd,omitempty"`
	OldSmContextRef            string                    `json:"oldSmContextRef,omitempty"`
	HplmnSnssai                *Snssai                   `json:"hplmnSnssai,omitempty"`
	AdditionalAnType           AccessType                `json:"additionalAnType,omitempty"`
	SamePcfSelectionInd        *bool                     `json:"samePcfSelectionInd,omitempty"`
	NrfManagementUri           string                    `json:"nrfManagementUri,omitempty"`
	SmContextSmfOauth2Required *bool                     `json:"smContextSmfOauth2Required,omitempty"`
	ServiceName                ServiceName               `json:"serviceName,omitempty"`
	HSmfId                     string                    `json:"hSmfId,omitempty"`
	RatType                    RatType                   `json:"ratType,omitempty"`
	TargetDnai                 string                    `json:"targetDnai,omitempty"`
	PduSessionId               *int                      `json:"pduSessionId,omitempty"`
	SelectedDnn                string                    `json:"selectedDnn,omitempty"`
	NrfUri                     string                    `json:"nrfUri,omitempty"`
	SmContextRef               string                    `json:"smContextRef,omitempty"`
	SmContextSmfPlmnId         *PlmnIdNid                `json:"smContextSmfPlmnId,omitempty"`
	SmfTransferInd             *bool                     `json:"smfTransferInd,omitempty"`
	NrfOauth2Required          map[string]bool           `json:"nrfOauth2Required,omitempty"`
	Dnn                        string                    `json:"dnn,omitempty"`
	UeTimeZone                 string                    `json:"ueTimeZone,omitempty"`
	SmfId                      string                    `json:"smfId,omitempty"`
	AdditionalSmfId            []string                  `json:"additionalSmfId,omitempty"`
	N2SmInfoType               N2SmInfoType              `json:"n2SmInfoType,omitempty"`
	SmContextSmfId             string                    `json:"smContextSmfId,omitempty"`
	OldSmfId                   string                    `json:"oldSmfId,omitempty"`
	SNssai                     *Snssai                   `json:"sNssai,omitempty"`
	SmfUri                     string                    `json:"smfUri,omitempty"`
	TraceData                  *TraceData                `json:"traceData,omitempty"`
	HNwPubKeyId                *int                      `json:"hNwPubKeyId,omitempty"`
	DirectForwardingFlag       *bool                     `json:"directForwardingFlag,omitempty"`
	CpCiotEnabled              *bool                     `json:"cpCiotEnabled,omitempty"`
	SmContextSmfServiceSetId   string                    `json:"smContextSmfServiceSetId,omitempty"`
	ExtendedNasSmTimerInd      *bool                     `json:"extendedNasSmTimerInd,omitempty"`
	N1SmMsg                    *RefToBinaryData          `json:"n1SmMsg,omitempty"`
	UeLocation                 *UserLocation             `json:"ueLocation,omitempty"`
	TngfInfo                   *TngfInfo                 `json:"tngfInfo,omitempty"`
	AddUeLocation              *UserLocation             `json:"addUeLocation,omitempty"`
	AdditionalSmfUri           []string                  `json:"additionalSmfUri,omitempty"`
	OldPduSessionId            *int                      `json:"oldPduSessionId,omitempty"`
	WAgfInfo                   *WAgfInfo                 `json:"wAgfInfo,omitempty"`
	NrfAccessTokenUri          string                    `json:"nrfAccessTokenUri,omitempty"`
	OldPduSessionRef           string                    `json:"oldPduSessionRef,omitempty"`
	Supi                       string                    `json:"supi,omitempty"`
	Gpsi                       string                    `json:"gpsi,omitempty"`
	DisasterRoamingInd         *bool                     `json:"disasterRoamingInd,omitempty"`
	SmPolicyNotifyInd          *bool                     `json:"smPolicyNotifyInd,omitempty"`
	UpipSupported              *bool                     `json:"upipSupported,omitempty"`
	RoutingIndicator           string                    `json:"routingIndicator,omitempty"`
}
