package models

type SmContextUpdateData struct {
	BackupAmfInfo                        []BackupAmfInfo                    `json:"backupAmfInfo,omitempty"`
	RatType                              string                             `json:"ratType,omitempty"`
	PresenceInLadn                       string                             `json:"presenceInLadn,omitempty"`
	SupportedFeatures                    string                             `json:"supportedFeatures,omitempty"`
	FailedToBeSwitched                   *bool                              `json:"failedToBeSwitched,omitempty"`
	N2SmInfoExt1                         *RefToBinaryData                   `json:"n2SmInfoExt1,omitempty"`
	N9UlForwardingTnlList                []IndirectDataForwardingTunnelInfo `json:"n9UlForwardingTnlList,omitempty"`
	RevokeEbiList                        []int                              `json:"revokeEbiList,omitempty"`
	Guami                                *Guami                             `json:"guami,omitempty"`
	EpsBearerSetup                       []string                           `json:"epsBearerSetup,omitempty"`
	N2SmInfoTypeExt1                     string                             `json:"n2SmInfoTypeExt1,omitempty"`
	Pei                                  string                             `json:"pei,omitempty"`
	AnType                               AccessType                         `json:"anType,omitempty"`
	UeLocation                           *UserLocation                      `json:"ueLocation,omitempty"`
	SmContextStatusUri                   string                             `json:"smContextStatusUri,omitempty"`
	MaReleaseInd                         string                             `json:"maReleaseInd,omitempty"`
	SkipN2PduSessionResRelInd            *bool                              `json:"skipN2PduSessionResRelInd,omitempty"`
	ExtendedNasSmTimerInd                *bool                              `json:"extendedNasSmTimerInd,omitempty"`
	ForwardingBearerContexts             []string                           `json:"forwardingBearerContexts,omitempty"`
	ServingNetwork                       *PlmnIdNid                         `json:"servingNetwork,omitempty"`
	DataForwarding                       *bool                              `json:"dataForwarding,omitempty"`
	MaRequestInd                         *bool                              `json:"maRequestInd,omitempty"`
	UpCnxState                           string                             `json:"upCnxState,omitempty"`
	N9DlForwardingTunnel                 *TunnelInfo                        `json:"n9DlForwardingTunnel,omitempty"`
	ServingNfId                          string                             `json:"servingNfId,omitempty"`
	AdditionalAnType                     AccessType                         `json:"additionalAnType,omitempty"`
	N9ForwardingTunnel                   *TunnelInfo                        `json:"n9ForwardingTunnel,omitempty"`
	Cause                                string                             `json:"cause,omitempty"`
	TraceData                            *TraceData                         `json:"traceData,omitempty"`
	SecondaryRatUsageDataReportContainer []string                           `json:"secondaryRatUsageDataReportContainer,omitempty"`
	AnTypeToReactivate                   AccessType                         `json:"anTypeToReactivate,omitempty"`
	N2SmInfoType                         string                             `json:"n2SmInfoType,omitempty"`
	N9DlForwardingTnlList                []IndirectDataForwardingTunnelInfo `json:"n9DlForwardingTnlList,omitempty"`
	SNssai                               *Snssai                            `json:"sNssai,omitempty"`
	MaNwUpgradeInd                       *bool                              `json:"maNwUpgradeInd,omitempty"`
	ExemptionInd                         *ExemptionInd                      `json:"exemptionInd,omitempty"`
	AddUeLocation                        *UserLocation                      `json:"addUeLocation,omitempty"`
	TargetId                             *NgRanTargetId                     `json:"targetId,omitempty"`
	NgApCause                            *NgApCause                         `json:"ngApCause,omitempty"`
	FiveGMmCauseValue                    *int                               `json:"5gMmCauseValue,omitempty"`
	EpsInterworkingInd                   string                             `json:"epsInterworkingInd,omitempty"`
	AnTypeCanBeChanged                   *bool                              `json:"anTypeCanBeChanged,omitempty"`
	HoState                              string                             `json:"hoState,omitempty"`
	TargetServingNfId                    string                             `json:"targetServingNfId,omitempty"`
	Release                              *bool                              `json:"release,omitempty"`
	MoExpDataCounter                     *MoExpDataCounter                  `json:"moExpDataCounter,omitempty"`
	ForwardingFTeid                      string                             `json:"forwardingFTeid,omitempty"`
	DdnFailureSubs                       *DdnFailureSubs                    `json:"ddnFailureSubs,omitempty"`
	SmPolicyNotifyInd                    *SmPolicyNotifyInd                 `json:"smPolicyNotifyInd,omitempty"`
	SatelliteBackhaulCat                 string                             `json:"satelliteBackhaulCat,omitempty"`
	ToBeSwitched                         *bool                              `json:"toBeSwitched,omitempty"`
	N9InactivityTimer                    *int                               `json:"n9InactivityTimer,omitempty"`
	PcfUeCallbackInfo                    *PcfUeCallbackInfo                 `json:"pcfUeCallbackInfo,omitempty"`
	UeTimeZone                           string                             `json:"ueTimeZone,omitempty"`
	N1SmMsg                              *RefToBinaryData                   `json:"n1SmMsg,omitempty"`
	N2SmInfo                             *RefToBinaryData                   `json:"n2SmInfo,omitempty"`
}
