package models

type SmContextCreateData struct {
	EpsBearerCtxStatus         string                 `json:"epsBearerCtxStatus,omitempty"`
	AdditionalHsmfId           []string               `json:"additionalHsmfId,omitempty"`
	HoState                    string                 `json:"hoState,omitempty"`
	BackupAmfInfo              []BackupAmfInfo        `json:"backupAmfInfo,omitempty"`
	TraceData                  *TraceData             `json:"traceData,omitempty"`
	InvokeNef                  *bool                  `json:"invokeNef,omitempty"`
	N2SmInfoType               string                 `json:"n2SmInfoType,omitempty"`
	N2SmInfoTypeExt1           string                 `json:"n2SmInfoTypeExt1,omitempty"`
	RanUnchangedInd            *bool                  `json:"ranUnchangedInd,omitempty"`
	PcfSetId                   string                 `json:"pcfSetId,omitempty"`
	NrfUri                     string                 `json:"nrfUri,omitempty"`
	OldPduSessionId            *int                   `json:"oldPduSessionId,omitempty"`
	NrfAccessTokenUri          string                 `json:"nrfAccessTokenUri,omitempty"`
	RequestType                string                 `json:"requestType,omitempty"`
	OldPduSessionRef           string                 `json:"oldPduSessionRef,omitempty"`
	HNwPubKeyId                *int                   `json:"hNwPubKeyId,omitempty"`
	IndirectForwardingFlag     *bool                  `json:"indirectForwardingFlag,omitempty"`
	TargetId                   *NgRanTargetId         `json:"targetId,omitempty"`
	CpCiotEnabled              *bool                  `json:"cpCiotEnabled,omitempty"`
	N2SmInfo                   *RefToBinaryData       `json:"n2SmInfo,omitempty"`
	SmContextSmfId             string                 `json:"smContextSmfId,omitempty"`
	SmfId                      string                 `json:"smfId,omitempty"`
	PcfGroupId                 string                 `json:"pcfGroupId,omitempty"`
	SatelliteBackhaulCat       string                 `json:"satelliteBackhaulCat,omitempty"`
	SmContextSmfOauth2Required *bool                  `json:"smContextSmfOauth2Required,omitempty"`
	PvsInfo                    []ServerAddressingInfo `json:"pvsInfo,omitempty"`
	PcfUeCallbackInfo          *PcfUeCallbackInfo     `json:"pcfUeCallbackInfo,omitempty"`
	SmfUri                     string                 `json:"smfUri,omitempty"`
	EpsInterworkingInd         string                 `json:"epsInterworkingInd,omitempty"`
	N2SmInfoExt1               *RefToBinaryData       `json:"n2SmInfoExt1,omitempty"`
	UpCnxState                 string                 `json:"upCnxState,omitempty"`
	TargetDnai                 string                 `json:"targetDnai,omitempty"`
	N1SmMsg                    *RefToBinaryData       `json:"n1SmMsg,omitempty"`
	HSmfUri                    string                 `json:"hSmfUri,omitempty"`
	HSmfId                     string                 `json:"hSmfId,omitempty"`
	AdditionalSmfUri           []string               `json:"additionalSmfUri,omitempty"`
	SelMode                    string                 `json:"selMode,omitempty"`
	UdmGroupId                 string                 `json:"udmGroupId,omitempty"`
	SmContextSmfPlmnId         *PlmnIdNid             `json:"smContextSmfPlmnId,omitempty"`
	UavAuthenticated           *bool                  `json:"uavAuthenticated,omitempty"`
	ServiceName                string                 `json:"serviceName,omitempty"`
	AdditionalAnType           string                 `json:"additionalAnType,omitempty"`
	AdditionalHsmfUri          []string               `json:"additionalHsmfUri,omitempty"`
	MaRequestInd               *bool                  `json:"maRequestInd,omitempty"`
	ApnRateStatus              *ApnRateStatus         `json:"apnRateStatus,omitempty"`
	SNssai                     *Snssai                `json:"sNssai,omitempty"`
	AnType                     string                 `json:"anType"`
	ServingNfId                string                 `json:"servingNfId"`
	CpOnlyInd                  *bool                  `json:"cpOnlyInd,omitempty"`
	SmContextSmfSetId          string                 `json:"smContextSmfSetId,omitempty"`
	NrfOauth2Required          *nrfOauth2Required     `json:"nrfOauth2Required,omitempty"`
	DisasterRoamingInd         *bool                  `json:"disasterRoamingInd,omitempty"`
	Supi                       string                 `json:"supi,omitempty"`
	UnauthenticatedSupi        *bool                  `json:"unauthenticatedSupi,omitempty"`
	SmContextStatusUri         string                 `json:"smContextStatusUri"`
	DdnFailureSubs             *DdnFailureSubs        `json:"ddnFailureSubs,omitempty"`
	SmContextRef               string                 `json:"smContextRef,omitempty"`
	DlDataWaitingInd           *bool                  `json:"dlDataWaitingInd,omitempty"`
	SmfTransferInd             *bool                  `json:"smfTransferInd,omitempty"`
	OldSmContextRef            string                 `json:"oldSmContextRef,omitempty"`
	SmfBindingInfo             string                 `json:"smfBindingInfo,omitempty"`
	HplmnSnssai                *Snssai                `json:"hplmnSnssai,omitempty"`
	Guami                      *Guami                 `json:"guami,omitempty"`
	RatType                    string                 `json:"ratType,omitempty"`
	MaNwUpgradeInd             *bool                  `json:"maNwUpgradeInd,omitempty"`
	AdditionalSmfId            []string               `json:"additionalSmfId,omitempty"`
	SamePcfSelectionInd        *bool                  `json:"samePcfSelectionInd,omitempty"`
	AnchorSmfOauth2Required    *bool                  `json:"anchorSmfOauth2Required,omitempty"`
	PresenceInLadn             string                 `json:"presenceInLadn,omitempty"`
	UeTimeZone                 string                 `json:"ueTimeZone,omitempty"`
	SelectedDnn                string                 `json:"selectedDnn,omitempty"`
	DirectForwardingFlag       *bool                  `json:"directForwardingFlag,omitempty"`
	SmContextSmfServiceSetId   string                 `json:"smContextSmfServiceSetId,omitempty"`
	TwifInfo                   *TwifInfo              `json:"twifInfo,omitempty"`
	SmPolicyNotifyInd          *bool                  `json:"smPolicyNotifyInd,omitempty"`
	Gpsi                       string                 `json:"gpsi,omitempty"`
	PduSessionId               *int                   `json:"pduSessionId,omitempty"`
	UeEpsPdnConnection         string                 `json:"ueEpsPdnConnection,omitempty"`
	PcfId                      string                 `json:"pcfId,omitempty"`
	SmContextSmfBinding        string                 `json:"smContextSmfBinding,omitempty"`
	SmallDataRateStatus        *SmallDataRateStatus   `json:"smallDataRateStatus,omitempty"`
	OldSmfId                   string                 `json:"oldSmfId,omitempty"`
	NrfManagementUri           string                 `json:"nrfManagementUri,omitempty"`
	UeLocation                 *UserLocation          `json:"ueLocation,omitempty"`
	PduSessionsActivateList    []int                  `json:"pduSessionsActivateList,omitempty"`
	OnboardingInd              *bool                  `json:"onboardingInd,omitempty"`
	UpipSupported              *bool                  `json:"upipSupported,omitempty"`
	ServingNetwork             PlmnIdNid              `json:"servingNetwork"`
	AddUeLocation              *UserLocation          `json:"addUeLocation,omitempty"`
	SupportedFeatures          string                 `json:"supportedFeatures,omitempty"`
	RoutingIndicator           string                 `json:"routingIndicator,omitempty"`
	ExtendedNasSmTimerInd      *bool                  `json:"extendedNasSmTimerInd,omitempty"`
	WAgfInfo                   *WAgfInfo              `json:"wAgfInfo,omitempty"`
	Pei                        string                 `json:"pei,omitempty"`
	Dnn                        string                 `json:"dnn,omitempty"`
	TngfInfo                   *TngfInfo              `json:"tngfInfo,omitempty"`
	NrfDiscoveryUri            string                 `json:"nrfDiscoveryUri,omitempty"`
}
