package models

type SmPolicyAssociationReleaseCause string

// Define constant values for SmPolicyAssociationReleaseCause
const (
	SMPOLICYASSOCIATIONRELEASECAUSE_UNSPECIFIED                  SmPolicyAssociationReleaseCause = "UNSPECIFIED"
	SMPOLICYASSOCIATIONRELEASECAUSE_UE_SUBSCRIPTION              SmPolicyAssociationReleaseCause = "UE_SUBSCRIPTION"
	SMPOLICYASSOCIATIONRELEASECAUSE_INSUFFICIENT_RES             SmPolicyAssociationReleaseCause = "INSUFFICIENT_RES"
	SMPOLICYASSOCIATIONRELEASECAUSE_VALIDATION_CONDITION_NOT_MET SmPolicyAssociationReleaseCause = "VALIDATION_CONDITION_NOT_MET"
	SMPOLICYASSOCIATIONRELEASECAUSE_REACTIVATION_REQUESTED       SmPolicyAssociationReleaseCause = "REACTIVATION_REQUESTED"
)
