package models
type SmPolicyUpdateContextData struct {
	 UeMac	string	`json:"ueMac,omitempty"`
	 NumOfPackFilter	*int	`json:"numOfPackFilter,omitempty"`
	 RepPolicyCtrlReqTriggers	[]string	`json:"repPolicyCtrlReqTriggers,omitempty"`
	 AddRelIpv6AddrPrefixes	string	`json:"addRelIpv6AddrPrefixes,omitempty"`
	 AuthProfIndex	string	`json:"authProfIndex,omitempty"`
	 TypesOfNotif	[]string	`json:"typesOfNotif,omitempty"`
	 MaPduInd	MaPduIndication	`json:"maPduInd,omitempty"`
	 InterGrpIds	[]string	`json:"interGrpIds,omitempty"`
	 RatType	RatType	`json:"ratType,omitempty"`
	 RelIpv4Address	string	`json:"relIpv4Address,omitempty"`
	 VplmnQosNotApp	*bool	`json:"vplmnQosNotApp,omitempty"`
	 UeInitResReq	*UeInitiatedResourceRequest	`json:"ueInitResReq,omitempty"`
	 InvalidPolicyDecs	[]InvalidParam	`json:"invalidPolicyDecs,omitempty"`
	 PccRuleId	string	`json:"pccRuleId,omitempty"`
	 AnGwStatus	*bool	`json:"anGwStatus,omitempty"`
	 AccessType	AccessType	`json:"accessType,omitempty"`
	 AddAccessInfo	*AdditionalAccessInfo	`json:"addAccessInfo,omitempty"`
	 TraceReq	*TraceData	`json:"traceReq,omitempty"`
	 TsnBridgeManCont	*BridgeManagementContainer	`json:"tsnBridgeManCont,omitempty"`
	 RelIpv6AddressPrefix	string	`json:"relIpv6AddressPrefix,omitempty"`
	 SubsSessAmbr	*Ambr	`json:"subsSessAmbr,omitempty"`
	 VplmnQos	*VplmnQos	`json:"vplmnQos,omitempty"`
	 PcfUeInfo	*PcfUeCallbackInfo	`json:"pcfUeInfo,omitempty"`
	 IpDomain	string	`json:"ipDomain,omitempty"`
	 SatBackhaulCategory	SatelliteBackhaulCategory	`json:"satBackhaulCategory,omitempty"`
	 ThreeGppPsDataOffStatus	*bool	`json:"3gppPsDataOffStatus,omitempty"`
	 RuleReports	[]RuleReport	`json:"ruleReports,omitempty"`
	 QosMonReports	[]QosMonitoringReport	`json:"qosMonReports,omitempty"`
	 ServNfId	*ServingNfIdentity	`json:"servNfId,omitempty"`
	 AccNetChIds	[]AccNetChId	`json:"accNetChIds,omitempty"`
	 AtsssCapab	AtsssCapability	`json:"atsssCapab,omitempty"`
	 TsnBridgeInfo	*TsnBridgeInfo	`json:"tsnBridgeInfo,omitempty"`
	 TsnPortManContDstt	*PortManagementContainer	`json:"tsnPortManContDstt,omitempty"`
	 RelAccessInfo	*AdditionalAccessInfo	`json:"relAccessInfo,omitempty"`
	 RefQosIndication	*bool	`json:"refQosIndication,omitempty"`
	 QosFlowUsage	QosFlowUsage	`json:"qosFlowUsage,omitempty"`
	 NwdafDatas	[]NwdafData	`json:"nwdafDatas,omitempty"`
	 MulAddrInfos	[]IpMulticastAddressInfo	`json:"mulAddrInfos,omitempty"`
	 PolicyDecFailureReports	[]string	`json:"policyDecFailureReports,omitempty"`
	 TrafficDescriptors	[]DddTrafficDescriptor	`json:"trafficDescriptors,omitempty"`
	 Ipv6AddressPrefix	string	`json:"ipv6AddressPrefix,omitempty"`
	 AddIpv6AddrPrefixes	string	`json:"addIpv6AddrPrefixes,omitempty"`
	 CreditManageStatus	CreditManagementStatus	`json:"creditManageStatus,omitempty"`
	 TsnPortManContNwtts	[]PortManagementContainer	`json:"tsnPortManContNwtts,omitempty"`
	 SessRuleReports	[]SessionRuleReport	`json:"sessRuleReports,omitempty"`
	 QncReports	[]QosNotificationControlInfo	`json:"qncReports,omitempty"`
	 Ipv4Address	string	`json:"ipv4Address,omitempty"`
	 AccuUsageReports	[]AccuUsageReport	`json:"accuUsageReports,omitempty"`
	 RepPraInfos	map[string]PresenceInfo	`json:"repPraInfos,omitempty"`
	 UeTimeZone	string	`json:"ueTimeZone,omitempty"`
	 ServingNetwork	*PlmnIdNid	`json:"servingNetwork,omitempty"`
	 RelUeMac	string	`json:"relUeMac,omitempty"`
	 SubsDefQos	*SubscribedDefaultQos	`json:"subsDefQos,omitempty"`
	 UserLocationInfoTime	string	`json:"userLocationInfoTime,omitempty"`
	 UserLocationInfo	*UserLocation	`json:"userLocationInfo,omitempty"`
	 AppDetectionInfos	[]AppDetectionInfo	`json:"appDetectionInfos,omitempty"`
}
