package models

// Define constant values for SupportedGADShapes
const (
	SUPPORTEDGADSHAPES_POINT                                string = "POINT"
	SUPPORTEDGADSHAPES_POINT_UNCERTAINTY_CIRCLE             string = "POINT_UNCERTAINTY_CIRCLE"
	SUPPORTEDGADSHAPES_POINT_UNCERTAINTY_ELLIPSE            string = "POINT_UNCERTAINTY_ELLIPSE"
	SUPPORTEDGADSHAPES_POLYGON                              string = "POLYGON"
	SUPPORTEDGADSHAPES_POINT_ALTITUDE                       string = "POINT_ALTITUDE"
	SUPPORTEDGADSHAPES_POINT_ALTITUDE_UNCERTAINTY           string = "POINT_ALTITUDE_UNCERTAINTY"
	SUPPORTEDGADSHAPES_ELLIPSOID_ARC                        string = "ELLIPSOID_ARC"
	SUPPORTEDGADSHAPES_LOCAL_2D_POINT_UNCERTAINTY_ELLIPSE   string = "LOCAL_2D_POINT_UNCERTAINTY_ELLIPSE"
	SUPPORTEDGADSHAPES_LOCAL_3D_POINT_UNCERTAINTY_ELLIPSOID string = "LOCAL_3D_POINT_UNCERTAINTY_ELLIPSOID"
)
