package models

// Define constant values for TrafficProfile
const (
	TRAFFICPROFILE_SINGLE_TRANS_UL     string = "SINGLE_TRANS_UL"
	TRAFFICPROFILE_SINGLE_TRANS_DL     string = "SINGLE_TRANS_DL"
	TRAFFICPROFILE_DUAL_TRANS_UL_FIRST string = "DUAL_TRANS_UL_FIRST"
	TRAFFICPROFILE_DUAL_TRANS_DL_FIRST string = "DUAL_TRANS_DL_FIRST"
	TRAFFICPROFILE_MULTI_TRANS         string = "MULTI_TRANS"
)
