package models

// Define constant values for TriggerType
const (
	TRIGGERTYPE_QUOTA_THRESHOLD                                  string = "QUOTA_THRESHOLD"
	TRIGGERTYPE_QHT                                              string = "QHT"
	TRIGGERTYPE_FINAL                                            string = "FINAL"
	TRIGGERTYPE_QUOTA_EXHAUSTED                                  string = "QUOTA_EXHAUSTED"
	TRIGGERTYPE_VALIDITY_TIME                                    string = "VALIDITY_TIME"
	TRIGGERTYPE_OTHER_QUOTA_TYPE                                 string = "OTHER_QUOTA_TYPE"
	TRIGGERTYPE_FORCED_REAUTHORISATION                           string = "FORCED_REAUTHORISATION"
	TRIGGERTYPE_UNUSED_QUOTA_TIMER                               string = "UNUSED_QUOTA_TIMER"
	TRIGGERTYPE_UNIT_COUNT_INACTIVITY_TIMER                      string = "UNIT_COUNT_INACTIVITY_TIMER"
	TRIGGERTYPE_ABNORMAL_RELEASE                                 string = "ABNORMAL_RELEASE"
	TRIGGERTYPE_QOS_CHANGE                                       string = "QOS_CHANGE"
	TRIGGERTYPE_VOLUME_LIMIT                                     string = "VOLUME_LIMIT"
	TRIGGERTYPE_TIME_LIMIT                                       string = "TIME_LIMIT"
	TRIGGERTYPE_EVENT_LIMIT                                      string = "EVENT_LIMIT"
	TRIGGERTYPE_PLMN_CHANGE                                      string = "PLMN_CHANGE"
	TRIGGERTYPE_USER_LOCATION_CHANGE                             string = "USER_LOCATION_CHANGE"
	TRIGGERTYPE_RAT_CHANGE                                       string = "RAT_CHANGE"
	TRIGGERTYPE_SESSION_AMBR_CHANGE                              string = "SESSION_AMBR_CHANGE"
	TRIGGERTYPE_UE_TIMEZONE_CHANGE                               string = "UE_TIMEZONE_CHANGE"
	TRIGGERTYPE_TARIFF_TIME_CHANGE                               string = "TARIFF_TIME_CHANGE"
	TRIGGERTYPE_MAX_NUMBER_OF_CHANGES_IN_CHARGING_CONDITIONS     string = "MAX_NUMBER_OF_CHANGES_IN_CHARGING_CONDITIONS"
	TRIGGERTYPE_MANAGEMENT_INTERVENTION                          string = "MANAGEMENT_INTERVENTION"
	TRIGGERTYPE_CHANGE_OF_UE_PRESENCE_IN_PRESENCE_REPORTING_AREA string = "CHANGE_OF_UE_PRESENCE_IN_PRESENCE_REPORTING_AREA"
	TRIGGERTYPE_CHANGE_OF_3GPP_PS_DATA_OFF_STATUS                string = "CHANGE_OF_3GPP_PS_DATA_OFF_STATUS"
	TRIGGERTYPE_SERVING_NODE_CHANGE                              string = "SERVING_NODE_CHANGE"
	TRIGGERTYPE_REMOVAL_OF_UPF                                   string = "REMOVAL_OF_UPF"
	TRIGGERTYPE_ADDITION_OF_UPF                                  string = "ADDITION_OF_UPF"
	TRIGGERTYPE_INSERTION_OF_ISMF                                string = "INSERTION_OF_ISMF"
	TRIGGERTYPE_REMOVAL_OF_ISMF                                  string = "REMOVAL_OF_ISMF"
	TRIGGERTYPE_CHANGE_OF_ISMF                                   string = "CHANGE_OF_ISMF"
	TRIGGERTYPE_START_OF_SERVICE_DATA_FLOW                       string = "START_OF_SERVICE_DATA_FLOW"
	TRIGGERTYPE_ECGI_CHANGE                                      string = "ECGI_CHANGE"
	TRIGGERTYPE_TAI_CHANGE                                       string = "TAI_CHANGE"
	TRIGGERTYPE_HANDOVER_CANCEL                                  string = "HANDOVER_CANCEL"
	TRIGGERTYPE_HANDOVER_START                                   string = "HANDOVER_START"
	TRIGGERTYPE_HANDOVER_COMPLETE                                string = "HANDOVER_COMPLETE"
	TRIGGERTYPE_GFBR_GUARANTEED_STATUS_CHANGE                    string = "GFBR_GUARANTEED_STATUS_CHANGE"
	TRIGGERTYPE_ADDITION_OF_ACCESS                               string = "ADDITION_OF_ACCESS"
	TRIGGERTYPE_REMOVAL_OF_ACCESS                                string = "REMOVAL_OF_ACCESS"
	TRIGGERTYPE_START_OF_SDF_ADDITIONAL_ACCESS                   string = "START_OF_SDF_ADDITIONAL_ACCESS"
	TRIGGERTYPE_REDUNDANT_TRANSMISSION_CHANGE                    string = "REDUNDANT_TRANSMISSION_CHANGE"
	TRIGGERTYPE_CGI_SAI_CHANGE                                   string = "CGI_SAI_CHANGE"
	TRIGGERTYPE_RAI_CHANGE                                       string = "RAI_CHANGE"
	TRIGGERTYPE_VSMF_CHANGE                                      string = "VSMF_CHANGE"
)
