package models

type UeContext struct {
	GroupList                  []string                        `json:"groupList,omitempty"`
	FiveGMmCapability          string                          `json:"5gMmCapability,omitempty"`
	HpcfSetId                  string                          `json:"hpcfSetId,omitempty"`
	CMsisdn                    string                          `json:"cMsisdn,omitempty"`
	RestrictedSecondaryRatList []string                        `json:"restrictedSecondaryRatList,omitempty"`
	LteCatMInd                 *bool                           `json:"lteCatMInd,omitempty"`
	MoExpDataCounter           *MoExpDataCounter               `json:"moExpDataCounter,omitempty"`
	PcfUeSliceMbrList          *pcfUeSliceMbrList              `json:"pcfUeSliceMbrList,omitempty"`
	UePolicyReqTriggerList     []string                        `json:"uePolicyReqTriggerList,omitempty"`
	RestrictedRatList          []string                        `json:"restrictedRatList,omitempty"`
	Supi                       string                          `json:"supi,omitempty"`
	SmallDataRateStatusInfos   []SmallDataRateStatusInfo       `json:"smallDataRateStatusInfos,omitempty"`
	CagData                    *CagData                        `json:"cagData,omitempty"`
	UePositioningCap           string                          `json:"uePositioningCap,omitempty"`
	WlServAreaRes              *WirelineServiceAreaRestriction `json:"wlServAreaRes,omitempty"`
	PcfRfsp                    *int                            `json:"pcfRfsp,omitempty"`
	UsedRfsp                   *int                            `json:"usedRfsp,omitempty"`
	HpcfId                     string                          `json:"hpcfId,omitempty"`
	ForbiddenAreaList          []Area                          `json:"forbiddenAreaList,omitempty"`
	EpsInterworkingInfo        *EpsInterworkingInfo            `json:"epsInterworkingInfo,omitempty"`
	IabOperationAllowed        *bool                           `json:"iabOperationAllowed,omitempty"`
	UpdpSubscriptionData       *UpdpSubscriptionData           `json:"updpSubscriptionData,omitempty"`
	SmsfSetId                  string                          `json:"smsfSetId,omitempty"`
	UdmGroupId                 string                          `json:"udmGroupId,omitempty"`
	AusfGroupId                string                          `json:"ausfGroupId,omitempty"`
	RoutingIndicator           string                          `json:"routingIndicator,omitempty"`
	ServiceAreaRestriction     *ServiceAreaRestriction         `json:"serviceAreaRestriction,omitempty"`
	RestrictedCoreNwTypeList   []string                        `json:"restrictedCoreNwTypeList,omitempty"`
	ImmediateMdtConf           *ImmediateMdtConf               `json:"immediateMdtConf,omitempty"`
	AstiDistributionIndication *bool                           `json:"astiDistributionIndication,omitempty"`
	EventSubscriptionList      []ExtAmfEventSubscription       `json:"eventSubscriptionList,omitempty"`
	SmPolicyNotifyPduList      []PduSessionInfo                `json:"smPolicyNotifyPduList,omitempty"`
	PcfUeCallbackInfo          *PcfUeCallbackInfo              `json:"pcfUeCallbackInfo,omitempty"`
	SupiUnauthInd              *bool                           `json:"supiUnauthInd,omitempty"`
	PcfGroupId                 string                          `json:"pcfGroupId,omitempty"`
	PcfUePolicyUri             string                          `json:"pcfUePolicyUri,omitempty"`
	StnSr                      string                          `json:"stnSr,omitempty"`
	SnpnOnboardInd             *bool                           `json:"snpnOnboardInd,omitempty"`
	SmfSelInfo                 *SmfSelectionData               `json:"smfSelInfo,omitempty"`
	DisasterRoamingInd         *bool                           `json:"disasterRoamingInd,omitempty"`
	PcfAmpServiceSetId         string                          `json:"pcfAmpServiceSetId,omitempty"`
	PcfBinding                 string                          `json:"pcfBinding,omitempty"`
	PcfAmpBindingInfo          string                          `json:"pcfAmpBindingInfo,omitempty"`
	UsedServiceAreaRestriction *ServiceAreaRestriction         `json:"usedServiceAreaRestriction,omitempty"`
	Pei                        string                          `json:"pei,omitempty"`
	DrxParameter               string                          `json:"drxParameter,omitempty"`
	PcfUepServiceSetId         string                          `json:"pcfUepServiceSetId,omitempty"`
	TraceData                  *TraceData                      `json:"traceData,omitempty"`
	AnalyticsSubscriptionList  []AnalyticsSubscription         `json:"analyticsSubscriptionList,omitempty"`
	PraInAmPolicy              *praInAmPolicy                  `json:"praInAmPolicy,omitempty"`
	GpsiList                   []string                        `json:"gpsiList,omitempty"`
	MmContextList              []MmContext                     `json:"mmContextList,omitempty"`
	SessionContextList         []PduSessionContext             `json:"sessionContextList,omitempty"`
	SmsfBindingInfo            string                          `json:"smsfBindingInfo,omitempty"`
	SmsfServiceSetId           string                          `json:"smsfServiceSetId,omitempty"`
	HNwPubKeyId                *int                            `json:"hNwPubKeyId,omitempty"`
	SubUeAmbr                  *Ambr                           `json:"subUeAmbr,omitempty"`
	PcfUeAmbr                  *Ambr                           `json:"pcfUeAmbr,omitempty"`
	SmsfId                     string                          `json:"smsfId,omitempty"`
	PcfId                      string                          `json:"pcfId,omitempty"`
	PcfAmPolicyUri             string                          `json:"pcfAmPolicyUri,omitempty"`
	ServiceGapExpiryTime       string                          `json:"serviceGapExpiryTime,omitempty"`
	ManagementMdtInd           *bool                           `json:"managementMdtInd,omitempty"`
	EcRestrictionDataWb        *EcRestrictionDataWb            `json:"ecRestrictionDataWb,omitempty"`
	TsErrorBudget              *int                            `json:"tsErrorBudget,omitempty"`
	DisasterPlmn               *PlmnId                         `json:"disasterPlmn,omitempty"`
	V2xContext                 *V2xContext                     `json:"v2xContext,omitempty"`
	EcRestrictionDataNb        *bool                           `json:"ecRestrictionDataNb,omitempty"`
	SubRfsp                    *int                            `json:"subRfsp,omitempty"`
	AmPolicyReqTriggerList     []string                        `json:"amPolicyReqTriggerList,omitempty"`
	RedCapInd                  *bool                           `json:"redCapInd,omitempty"`
	PraInUePolicy              *praInUePolicy                  `json:"praInUePolicy,omitempty"`
	SubUeSliceMbrList          *subUeSliceMbrList              `json:"subUeSliceMbrList,omitempty"`
	SeafData                   *SeafData                       `json:"seafData,omitempty"`
	PcfSetId                   string                          `json:"pcfSetId,omitempty"`
	MsClassmark2               string                          `json:"msClassmark2,omitempty"`
	SupportedCodecList         []string                        `json:"supportedCodecList,omitempty"`
	RestrictedPrimaryRatList   []string                        `json:"restrictedPrimaryRatList,omitempty"`
	ProseContext               *ProseContext                   `json:"proseContext,omitempty"`
	AsTimeDisParam             *AsTimeDistributionParam        `json:"asTimeDisParam,omitempty"`
	PcfUepBindingInfo          string                          `json:"pcfUepBindingInfo,omitempty"`
}
