package models

// Define constant values for WlanOrderingCriterion
const (
	WLANORDERINGCRITERION_TIME_SLOT_START string = "TIME_SLOT_START"
	WLANORDERINGCRITERION_NUMBER_OF_UES   string = "NUMBER_OF_UES"
	WLANORDERINGCRITERION_RSSI            string = "RSSI"
	WLANORDERINGCRITERION_RTT             string = "RTT"
	WLANORDERINGCRITERION_TRAFFIC_INFO    string = "TRAFFIC_INFO"
)
